function postbody() { document.write('' 
+'<div id="wrapper">\n'
+'<center>\n'
+'\n'
+'<img src="http://aikidou.localhost:473/img/banner1000.jpg" alt="banner">\n'
+'<div class="navbar">\n'
+'  <div class="navbar-inner">\n'
+'    <div class="container">\n'
+'\n'
+'<!-- Begin -->    \n'
+'<ul class="nav">\n'
+'<li><a href="http://aikidou.localhost:473/?">home</a></li>\n'
+'<li><a href="http://aikidou.localhost:473/?page=contact">contact</a></li>\n'
+'<li class="dropdown">\n'
+'    <a href="#" class="dropdown-toggle" data-toggle="dropdown">\n'
+'        commisies&nbsp;<b class="caret"></b></a>\n'
+'    <ul class="dropdown-menu">\n'
+'        <li><a href="http://aikidou.localhost:473/?page=nca">NCA</a></li>\n'
+'        <li><a href="http://aikidou.localhost:473/?page=ncoa">NCOA</a></li>\n'
+'        <li><a href="http://aikidou.localhost:473/?page=ngca">NGCA</a></li>\n'
+'    </ul>\n'
+'</li>\n'
+'<li><a href="http://aikidou.localhost:473/?page=examens">examens</a></li>\n'
+'<li><a href="http://aikidou.localhost:473/?page=fotos">fotos</a></li>\n'
+'<li class="dropdown">\n'
+'    <a href="#" class="dropdown-toggle" data-toggle="dropdown">\n'
+'        kalender&nbsp;<b class="caret"></b></a>\n'
+'    <ul class="dropdown-menu">\n'
+'        <li><a href="http://aikidou.localhost:473/?page=kalender">kalender</a></li>\n'
+'        <li><a href="http://aikidou.localhost:473/?page=kalender_event">event aanmelden</a></li>\n'
+'        <li><a href="http://aikidou.localhost:473/?page=kalender_hulp">hulp voor kalender</a></li>\n'
+'    </ul>\n'
+'</li>\n'
+'<li><a href="http://aikidou.localhost:473/?page=nieuws">nieuws</a></li>\n'
+'<li><a href="http://aikidou.localhost:473/?page=opleidingen">opleidingen</a></li>\n'
+'<li class="dropdown">\n'
+'    <a href="#" class="dropdown-toggle" data-toggle="dropdown">\n'
+'        stijl&nbsp;<b class="caret"></b></a>\n'
+'    <ul class="dropdown-menu">\n'
+'        <li><a href="http://aikidou.localhost:473/?page=aikibudo">aiki budo</a></li>\n'
+'        <li><a href="http://aikidou.localhost:473/?page=aikikai_aikido">aikikai aikido</a></li>\n'
+'        <li><a href="http://aikidou.localhost:473/?page=ki_aikido">ki aikido</a></li>\n'
+'    </ul>\n'
+'</li>\n'
+'</ul><!-- nav --> \n'
+'    </div>\n'
+'  </div>\n'
+'</div> <!-- navbar -->\n'
+'\n'
+'<div><!-- do not use [div id="contents"], reason: width: ... --> \n'
+'\n'
); }