<?php
// leraren.php, generated file 2018-09-07 13:05:12
define("AIKIBUDO_STAGE",              "Aikibudo stage");
define("AIKIBUDO_STAGE_T",            "aikido_t.jpg");
define("AD_VAN_DONGEN",               "Ad van Dongen");
define("AD_VAN_DONGEN_T",             "aikido_t.jpg");
define("ALAIN_FLOQUET",               "Alain Floquet sensei 9e dan");
define("ALAIN_FLOQUET_T",             "alain_floquet_t.jpg");
define("AIKIDOFESTIJN",               "Aikidofestijn");
define("AIKIDOFESTIJN_T",             "aikidofestijn_t.jpg");
define("ALAIN_ROINEL",                "Alain Roinel");
define("ALAIN_ROINEL_T",              "alain_roinel_t.jpg");
define("AD_VOGELS",                   "Ad Voogels");
define("AD_VOGELS_T",                 "aikido_t.jpg");
define("BENT",                        "Bent Bervoets");
define("BENT_T",                      "aikido_t.jpg");
define("CURTIS",                      "Chris Curtis 8de dan");
define("CURTIS_T",                    "curtis_t.jpg");
define("CHRIS",                       "Chris de Jongh 6de dan");
define("CHRIS_T",                     "chris_t.jpg");
define("CAROOL",                      "Carool Janssen");
define("CAROOL_T",                    "aikido_t.jpg");
define("CLAUDE",                      "Claude Pellerin 7de dan shihan");
define("CLAUDE_T",                    "claude_t.jpg");
define("CAREL",                       "Carel Zappeij 7de dan shihan");
define("CAREL_T",                     "carel_t.jpg");
define("DANIEL_DUBREUIL",             "Daniel Dubreuil 7de dan");
define("DANIEL_DUBREUIL_T",           "aikido_t.jpg");
define("DENNIS",                      "Dennis Goedbloed");
define("DENNIS_T",                    "aikido_t.jpg");
define("DIMME",                       "Dimme van der Hout");
define("DIMME_T",                     "aikido_t.jpg");
define("DISTRICT_STAGE",              "Districtstage");
define("DISTRICT_STAGE_T",            "aikido_t.jpg");
define("DIRK_MULLER",                 "Dirk Muller");
define("DIRK_MULLER_T",               "aikido_t.jpg");
define("DONOVAN",                     "Donovan Waite 7de dan shihan");
define("DONOVAN_T",                   "donovan_t.jpg");
define("EXAMENS",                     "Examens");
define("EXAMENS_T",                   "examens_t.jpg");
define("EXAMEN_VOORBEREIDING",        "Danexamentraining");
define("EXAMEN_VOORBEREIDING_T",      "examen_voorbereiding_t.jpg");
define("FREDERIQUE_FLOQUET",          "Frederique Floquet");
define("FREDERIQUE_FLOQUET_T",        "aikido_t.jpg");
define("FUKAKUSA",                    "Fukakusa 8ste dan shihan");
define("FUKAKUSA_T",                  "fukakusa_t.jpg");
define("GABOR",                       "G&aacute;bor J&aacute;nosi");
define("GABOR_T",                     "aikido_t.jpg");
define("GIJS",                        "Gijs Schouten");
define("GIJS_T",                      "aikido_t.jpg");
define("HARRY_KAT",                   "Harry Kat 6de dan");
define("HARRY_KAT_T",                 "aikido_t.jpg");
define("HANS_BELDER",                 "Hans Belder 6de dan");
define("HANS_BELDER_T",               "aikido_t.jpg");
define("HENK_KAT",                    "Henk Kat 6de dan");
define("HENK_KAT_T",                  "aikido_t.jpg");
define("HANS_MERTENS",                "Hans Mertens");
define("HANS_MERTENS_T",              "aikido_t.jpg");
define("IAS",                         "IAS");
define("IAS_T",                       "ias_t.jpg");
define("JAN_BRAND",                   "Jan Brand 6de dan");
define("JAN_BRAND_T",                 "aikido_t.jpg");
define("JAN_RUSMAN",                  "Jan Rusman 6de dan");
define("JAN_RUSMAN_T",                "aikido_t.jpg");
define("LEONARD",                     "Leonard van Kuijk");
define("LEONARD_T",                   "aikido_t.jpg");
define("LOUIS",                       "Louis van Thieghem 7de dan shihan");
define("LOUIS_T",                     "louis_t.jpg");
define("MAARTEN",                     "Maarten Huiskamp");
define("MAARTEN_T",                   "aikido_t.jpg");
define("MICKAEL",                     "Mickael Martin");
define("MICKAEL_T",                   "mickael_t.jpg");
define("MARCEL",                      "Marcel Mutsaarts");
define("MARCEL_T",                    "aikido_t.jpg");
define("MALCOM",                      "Malcom Tiki Shewan");
define("MALCOM_T",                    "malcom_t.jpg");
define("PIERRE",                      "Pierre Geraedts 7de dan shihan");
define("PIERRE_T",                    "pierre_t.jpg");
define("RONALD",                      "Ronald Jansen");
define("RONALD_T",                    "aikido_t.jpg");
define("STEPHANE",                    "Stephane Benedetti");
define("STEPHANE_T",                  "stephane_t.jpg");
define("TESSA",                       "Tessa Huiskamp");
define("TESSA_T",                     "aikido_t.jpg");
define("WILKO",                       "Wilko Lok");
define("WILKO_T",                     "aikido_t.jpg");
define("WAKA",                        "Waka sensei");
define("WAKA_T",                      "waka_t.jpg");
define("WYTSKE",                      "Wytske de Wit");
define("WYTSKE_T",                    "aikido_t.jpg");
define("YUDANSHA",                    "Yudansha");
define("YUDANSHA_T",                  "aikido_t.jpg");
?>
