<?php
// leraren.php, generated file 2018-01-01 19:53:31
define("AD_VAN_DONGEN", "Ad van Dongen");
define("AD_VAN_DONGEN_T", "NO_T");
define("FLOQUET", "Alain Floquet sensei 9e dan");
define("FLOQUET_T", "floquet_t.jpg");
define("AIKIDOFESTIJN", "Aikidofestijn");
define("AIKIDOFESTIJN_T", "aikidofestijn_t.jpg");
define("ROINEL", "Alain Roinel");
define("ROINEL_T", "roinel_t.jpg");
define("AD_VOGELS", "Ad Voogels");
define("AD_VOGELS_T", "NO_T");
define("BENT", "Bent Bervoets");
define("BENT_T", "NO_T");
define("CURTIS", "Chris Curtis 7de dan");
define("CURTIS_T", "curtis_t.jpg");
define("CHRIS_DE_JONGH", "Chris de Jongh");
define("CHRIS_DE_JONGH_T", "NO_T");
define("CAROOL", "Carool Janssen");
define("CAROOL_T", "NO_T");
define("CLAUDE", "Claude Pellerin 7de dan shihan");
define("CLAUDE_T", "claude_t.jpg");
define("CAREL", "Carel Zappey 7de dan");
define("CAREL_T", "carel_t.jpg");
define("DISTRICT_STAGE", "Districtstage");
define("DISTRICT_STAGE_T", "NO_T");
define("DIRK_MULLER", "Dirk Muller");
define("DIRK_MULLER_T", "dirk_t.jpg");
define("EXAMEN_VOORBEREIDING", "Danexamentraining");
define("EXAMEN_VOORBEREIDING_T", "examen_voorbereiding_t.jpg");
define("EXAMENS", "Examens");
define("EXAMENS_T", "examens_t.jpg");
define("FLOQUETF", "Frederique Floquet");
define("FLOQUETF_T", "NO_T");
define("FUKAKUSA", "Fukakusa 8ste dan shihan");
define("FUKAKUSA_T", "fukakusa_t.jpg");
define("GIJS", "Gijs Schouten");
define("GIJS_T", "NO_T");
define("HARRY_KAT", "Harry Kat");
define("HARRY_KAT_T", "NO_T");
define("HANS_BELDER", "Hans Belder");
define("HANS_BELDER_T", "NO_T");
define("HENK_KAT", "Henk Kat");
define("HENK_KAT_T", "NO_T");
define("HANS_MERTENS", "Hans Mertens");
define("HANS_MERTENS_T", "NO_T");
define("IAS", "IAS");
define("IAS_T", "ias_t.jpg");
define("JAN_BRAND", "Jan Brand");
define("JAN_BRAND_T", "NO_T");
define("JAN_RUSMAN", "Jan Rusman");
define("JAN_RUSMAN_T", "NO_T");
define("LEONARD", "Leonard van Kuijk");
define("LEONARD_T", "NO_T");
define("LOUIS", "Louis van Thieghem 7de dan shihan");
define("LOUIS_T", "louis_t.jpg");
define("MAARTEN", "Maarten Huiskamp");
define("MAARTEN_T", "NO_T");
define("MICKAEL", "Mickael Martin");
define("MICKAEL_T", "mickael_t.jpg");
define("MARCEL", "Marcel Mutsaarts");
define("MARCEL_T", "NO_T");
define("MALCOM", "Malcom Tiki Shewan");
define("MALCOM_T", "malcom_t.jpg");
define("PIERRE", "Pierre Geraedts 7de dan");
define("PIERRE_T", "pierre_t.jpg");
define("RONALD", "Ronald Jansen");
define("RONALD_T", "NO_T");
define("STEPHANE", "Stephane Benedetti");
define("STEPHANE_T", "stephane_t.jpg");
define("TESSA", "Tessa Huiskamp");
define("TESSA_T", "NO_T");
?>
