<?php
// locaties.php, generated file 2017-02-22 20:33:45
define("ALKMAAR", "Alkmaar");
define("ALKMAAR_L", "Vondelstraat 35, Alkmaar");
define("AMERSFOORT", "Amersfoort");
define("AMERSFOORT_L", "Furglerplein 3, Amersfoort");
define("AMSTELVEEN", "Amstelveen");
define("AMSTELVEEN_L", "Doctor Schaepmanlaan 2, Amstelveen");
define("ARNHEM_PAPENDAL", "Arnhem");
define("ARNHEM_PAPENDAL_L", "Papendallaan, Arnhem");
define("DEN_HAAG", "Den Haag ");
define("DEN_HAAG_L", "Baambruggestraat 8a, Den Haag ");
define("DISTRICT_LI", "Limburg");
define("DISTRICT_LI_L", "Limburg");
define("DISTRICT_MN", "midden Nederland");
define("DISTRICT_MN_L", "midden Nederland");
define("DISTRICT_NH", "noord Holland");
define("DISTRICT_NH_L", "noord Holland");
define("DISTRICT_NN", "noord Nederland");
define("DISTRICT_NN_L", "noord Nederland");
define("DISTRICT_ZH", "zuid Holland");
define("DISTRICT_ZH_L", "zuid Holland");
define("DISTRICT_ZN", "zuid Nederland");
define("DISTRICT_ZN_L", "zuid Nederland");
define("EINDHOVEN", "Eindhoven");
define("EINDHOVEN_L", "Theo Koomenlaan 3, Eindhoven");
define("EEN_WEST", "Een-West");
define("EEN_WEST_L", "Jarig van de Wielenwei 42, Een-West");
define("GENNEP", "Gennep");
define("GENNEP_L", "Picardie 36, Gennep");
define("HAARLEM_BYZANTIUM", "Haarlem");
define("HAARLEM_BYZANTIUM_L", "Byzantiumstraat 74, Haarlem");
define("HAARLEM_IJSBAAN", "Haarlem");
define("HAARLEM_IJSBAAN_L", "IJsbaanlaan 4A, Haarlem");
define("HELMOND", "Helmond");
define("HELMOND_L", "Barrierlaan 41, Helmond");
define("HEERHUGOWAARD", "Heerhugowaard");
define("HEERHUGOWAARD_L", "Dudokweg 20, Heerhugowaard");
define("HILLEGOM", "Hillegom");
define("HILLEGOM_L", "Abellalaan 82, Hillegom");
define("HEERENVEEN", "Heerenveen");
define("HEERENVEEN_L", "Abe Lenstra boulevard 23Q, Heerenveen");
define("LEEUWARDEN", "Leeuwarden");
define("LEEUWARDEN_L", "Emmakade 59, Leeuwarden");
define("LELYSTAD", "Lelystad");
define("LELYSTAD_L", "Badweg 21, Lelystad");
define("NIEUWEGEIN", "Nieuwegein");
define("NIEUWEGEIN_L", "Blokhoeve 5, Nieuwegein");
define("NIJMEGEN", "Nijmegen");
define("NIJMEGEN_L", "Tapirstraat 2, Nijmegen");
define("NOG_NIET_BEKEND", "");
define("NOG_NIET_BEKEND_L", "Nog niet bekend");
define("OOSTERHOUT", "Oosterhout");
define("OOSTERHOUT_L", "Slotjesveld 9, Oosterhout");
define("ROERMOND", "Roermond");
define("ROERMOND_L", "Prins Bernhardstraat 1a, Roermond");
define("SITTARD", "Sittard");
define("SITTARD_L", "Valkstraat 2, Sittard");
define("STROE", "Stroe");
define("STROE_L", "Tolnegenweg 53, Stroe");
define("TETERINGEN", "Teteringen (Breda)");
define("TETERINGEN_L", "Kriekenstraat 43, Teteringen (Breda)");
define("VEGHEL", "Veghel");
define("VEGHEL_L", "Prins Willem Alexander Sportpark 7, Veghel");
define("VIANEN", "Vianen");
define("VIANEN_L", "Westelijke Parrallelweg 1, Vianen");
define("WAGENINGEN", "Wageningen");
define("WAGENINGEN_L", "Nieuwe Kanaal 11, Wageningen");
define("WIJK_BIJ_DUURSTEDE", "Wijk bij Duurstede");
define("WIJK_BIJ_DUURSTEDE_L", "Lekdijk oost 13a, Wijk bij Duurstede");
define("ZAANDAM", "Zaandam");
define("ZAANDAM_L", "Panneroodstraat 1, Zaandam");
?>
